[package]
name = "smithy"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
rayon = "1.10"
ndarray = "0.15"
ndarray-rand = "0.15"
rand = "0.8"
rand_distr = "0.4"

[lib]
crate-type = ["cdylib"]